version: '2'
services:
  web:
    build: .
    ports:
        - "8080:8080"
    environment:
      APPLICATION_ENV: Production
    links:
      - mongodb
    depends_on:
      - mongodb

  frontend:
    build: frontend/
    ports:
        - "8081:80"
    depends_on:
      - web

  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data

volumes:
  mongodbdata:
