web:
  build: .
  command: bash -c "python setup.py && gunicorn gunicorn run:app --bind 0.0.0.0:8001 --access-logfile=logs/gunicorn-access.log --error-logfile logs/gunicorn-error.log"
  ports:
      - "8001:8001"
  volumes:
    - ./:/app-container
  environment:
    APPLICATION_ENV: Production

  links:
    - mongodb

mongodb:
  image: mongo
  hostname: mongodb